### ISSUE TITLE
Geometry class in registerCoreCodecs

### ISSUE THREAD

**Issue by ChaoqiYin** [maxGraph/maxgraph#369] opened 2024-03-25 01:52 UTC
i’m using webpack to build my project with mode: 'production'，when i export the xml，the @maxgraph/core will not encode geometry element to <Geometry.../>，because webpack will replace the Geometry class's constructor.name。

**Comment by tbouffard** [comment] 2024-03-25 08:08
What is the maxGraph version you are using? #309 fixed most problems related to minification in version 0.7.0.

This seems to be a duplicate of #327.
If you don't think this is a duplicate, please provides more details about your use case (please provide code sample or repository to let other reproduce the problem).

**Comment by ChaoqiYin** [comment] 2024-03-26 02:08
i'm using 0.8.0 with yarn，the webpack build config is 
```javascript
{
    mode: 'production',
    entry: './src/index.js',
    output: {
        clean: true,
        path: path.resolve(__dirname, 'lib'),
        filename: 'bow-tie.js',
        library: {
            name: 'bowTie',
            type: 'umd'
        }
    }
}
```

the index.js is export 
```javascript
class Bowtie {
    constructor(container) {
        this.container = container;
        this.initGraph();
    }

    initGraph() {
        this.graph = new BowtieGraph(this.container);

   ....

    import(xmlStr) {
        new ModelXmlSerializer(this.graph.getDataModel()).import(xmlStr);
    }

    export() {
        return new ModelXmlSerializer(this.graph.getDataModel()).export();
    }
}
```

**Comment by tbouffard** [comment] 2024-03-26 08:27
OK thanks, the configuration looks similar to our webpack example available in packages/js-example.

Can you provide an extract of the xml you get with the geometry data not correctly encoded?
This is to compare with the XML mentioned in #327.

**Closed as completed** 2024-07-05 09:04 UTC
Labels: bug, duplicate
