### ISSUE TITLE
Whether Canvas Is Supported

### ISSUE THREAD

**Issue by asreday** [maxGraph/maxGraph#9] opened 2021-03-29 03:18 UTC
If too many svg nodes cause frame freezing, how to optimize the problem?

**Comment by tbouffard** [comment] 2021-03-29 05:54
mxGraph currently only generates SVG: https://jgraph.github.io/mxgraph/docs/manual.html#1.4 and is not designed to display a large amount of svg nodes.

**Comment by coclav** [comment] 2021-04-07 09:26
what are you trying to do in the first place ?

**Comment by asreday** [comment] 2021-04-08 06:10
> what are you trying to do in the first place ?

Do a large circuit diagram observation, about a few hundred plot points

**Comment by tbouffard** [comment] 2021-04-08 08:37
@asreday please have a look at https://github.com/jgraph/mxgraph/issues/204 or https://github.com/jgraph/mxgraph/issues/265#issuecomment-654112783 to get more insights about the number of nodes `mxGraph` can currently displays.

**Comment by tbouffard** [comment] 2023-03-01 05:26
A new discussion on this topic has just begun in #180.

**Comment by tbouffard** [comment] 2023-07-06 04:04
Closing this issue as duplicate of #180.

**Closed as not planned** 2023-07-06 04:04 UTC
Labels: question
