### ISSUE TITLE
Loading from XML not working after Build

### ISSUE THREAD

**Issue by g136660** [maxGraph/maxgraph#197] opened 2023-06-01 08:15 UTC
```js
var xmlDoc: Document = xmlUtils.parseXml(xml);
var codec = new Codec(xmlDoc);
codec.decode(xmlDoc.documentElement, graph.model);
```

This code work fine in VS code and debug mode.
But not working after build and deploy on IIS or console

xml:
```xml
"<GraphDataModel><root><Cell id=\"0\"><Object as=\"style\"/></Cell><Cell id=\"1\" parent=\"0\"><Object as=\"style\"/></Cell><div Text=\"АРТ. {0}\" BarcodeFormat=\"\" Fields=\"[&quot;GoodsCode&quot;]\" id=\"5\"><Cell vertex=\"1\" connectable=\"0\" parent=\"1\"><Geometry _x=\"81\" _y=\"8.49999975\" _width=\"75\" _height=\"7\" as=\"geometry\"/><Object fontSize=\"5\" align=\"left\" verticalAlign=\"top\" whiteSpace=\"wrap\" overflow=\"hidden\" fontFamily=\"Arial\" fontStyle=\"0\" rotation=\"0\" fontColor=\"black\" fillColor=\"#ffffff\" strokeColor=\"#2946eb\" strokeWidth=\"0.5\" labelPadding=\"0\" as=\"style\"><Array as=\"baseStyleNames\"><add value=\"yeah\"/></Array></Object></Cell></div><div Text=\"EAC\" BarcodeFormat=\"\" Fields=\"[]\" id=\"6\"><Cell vertex=\"1\" connectable=\"0\" parent=\"1\"><Geometry _x=\"8.5\" _y=\"8\" _width=\"65.5\" _height=\"30\" TRANSLATE_CONTROL_POINTS=\"0\" as=\"geometry\"/><Object fontSize=\"22\" align=\"center\" verticalAlign=\"top\" whiteSpace=\"wrap\" overflow=\"hidden\" fontFamily=\"Arial\" fontStyle=\"1\" rotation=\"0\" fontColor=\"black\" fillColor=\"#ffffff\" strokeColor=\"#2946eb\" strokeWidth=\"0.5\" labelPadding=\"0\" as=\"style\"><Array as=\"baseStyleNames\"><add value=\"yeah\"/></Array></Object></Cell></div><div Text=\"Изг. {0:dd.MM.yyyy}\" BarcodeFormat=\"\" Fields=\"[&quot;ManufactureDate&quot;]\" id=\"7\"><Cell vertex=\"1\" connectable=\"0\" parent=\"1\"><Geometry _x=\"81\" _y=\"15\" _width=\"75\" _height=\"7\" as=\"geometry\"/><Object fontSize=\"5\" align=\"left\" verticalAlign=\"top\" whiteSpace=\"wrap\" overflow=\"hidden\" fontFamily=\"Arial\" fontStyle=\"0\" rotation=\"0\" fontColor=\"black\" fillColor=\"#ffffff\" strokeColor=\"#2946eb\" strokeWidth=\"0.5\" labelPadding=\"0\" as=\"style\"><Array as=\"baseStyleNames\"><add value=\"yeah\"/></Array></Object></Cell></div><div Text=\"Страна {0}\" BarcodeFormat=\"\" Fields=\"[&quot;CountryName&quot;]\" id=\"8\"><Cell vertex=\"1\" connectable=\"0\" parent=\"1\"><Geometry _x=\"81\" _y=\"22\" _width=\"75\" _height=\"7\" as=\"geometry\"/><Object fontSize=\"5\" align=\"left\" verticalAlign=\"top\" whiteSpace=\"wrap\" overflow=\"hidden\" fontFamily=\"Arial\" fontStyle=\"0\" rotation=\"0\" fontColor=\"black\" fillColor=\"#ffffff\" strokeColor=\"#2946eb\" strokeWidth=\"0.5\" labelPadding=\"0\" as=\"style\"><Array as=\"baseStyleNames\"><add value=\"yeah\"/></Array></Object></Cell></div><div Text=\"Бренд {0}\" BarcodeFormat=\"\" Fields=\"[&quot;CollectionName&quot;]\" id=\"9\"><Cell vertex=\"1\" connectable=\"0\" parent=\"1\"><Geometry _x=\"81\" _y=\"29\" _width=\"75\" _height=\"7\" as=\"geometry\"/><Object fontSize=\"5\" align=\"left\" verticalAlign=\"top\" whiteSpace=\"wrap\" overflow=\"hidden\" fontFamily=\"Arial\" fontStyle=\"0\" rotation=\"0\" fontColor=\"black\" fillColor=\"#ffffff\" strokeColor=\"#2946eb\" strokeWidth=\"0.5\" labelPadding=\"0\" as=\"style\"><Array as=\"baseStyleNames\"><add value=\"yeah\"/></Array></Object></Cell></div><div Text=\"{0}        РАЗМ.{1}\" BarcodeFormat=\"\" Fields=\"[&quot;Gender&quot;,&quot;SizeEu&quot;]\" id=\"10\"><Cell vertex=\"1\" connectable=\"0\" parent=\"1\"><Geometry _x=\"81\" _y=\"36\" _width=\"75\" _height=\"7\" as=\"geometry\"/><Object fontSize=\"5\" align=\"left\" verticalAlign=\"top\" whiteSpace=\"wrap\" overflow=\"hidden\" fontFamily=\"Arial\" fontStyle=\"0\" rotation=\"0\" fontColor=\"black\" fillColor=\"#ffffff\" strokeColor=\"#2946eb\" strokeWidth=\"0.5\" labelPadding=\"0\" as=\"style\"><Array as=\"baseStyleNames\"><add value=\"yeah\"/></Array></Object></Cell></div><div Text=\"{0}\" BarcodeFormat=\"\" Fields=\"[&quot;GoodsName&quot;]\" id=\"11\"><Cell vertex=\"1\" connectable=\"0\" parent=\"1\"><Geometry _x=\"8.49999975\" _y=\"43\" _width=\"147.5\" _height=\"9\" as=\"geometry\"/><Object fontSize=\"7\" align=\"left\" verticalAlign=\"top\" whiteSpace=\"wrap\" overflow=\"hidden\" fontFamily=\"Arial\" fontStyle=\"1\" rotation=\"0\" fontColor=\"black\" fillColor=\"#ffffff\" strokeColor=\"#2946eb\" strokeWidth=\"0.5\" labelPadding=\"0\" as=\"style\"><Array as=\"baseStyleNames\"><add value=\"yeah\"/></Array></Object></Cell></div><div Text=\"{0}\" BarcodeFormat=\"\" Fields=\"[&quot;Consist&quot;]\" id=\"12\"><Cell vertex=\"1\" connectable=\"0\" parent=\"1\"><Geometry _x=\"8.5\" _y=\"52\" _width=\"147.5\" _height=\"15\" as=\"geometry\"/><Object fontSize=\"6\" align=\"left\" verticalAlign=\"top\" whiteSpace=\"wrap\" overflow=\"hidden\" fontFamily=\"Arial\" fontStyle=\"0\" rotation=\"0\" fontColor=\"black\" fillColor=\"#ffffff\" strokeColor=\"#2946eb\" strokeWidth=\"0.5\" labelPadding=\"0\" as=\"style\"><Array as=\"baseStyleNames\"><add value=\"yeah\"/></Array></Object></Cell></div><div Text=\"Юр.адрес: {0}\" BarcodeFormat=\"\" Fields=\"[&quot;Address&quot;]\" id=\"13\"><Cell vertex=\"1\" connectable=\"0\" parent=\"1\"><Geometry _x=\"8.5\" _y=\"74\" _width=\"147.5\" _height=\"10\" as=\"geometry\"/><Object fontSize=\"4\" align=\"left\" verticalAlign=\"top\" whiteSpace=\"wrap\" overflow=\"hidden\" fontFamily=\"Arial\" fontStyle=\"1\" rotation=\"0\" fontColor=\"black\" fillColor=\"#ffffff\" strokeColor=\"#2946eb\" strokeWidth=\"0.5\" labelPadding=\"0\" as=\"style\"><Array as=\"baseStyleNames\"><add value=\"yeah\"/></Array></Object></Cell></div><div Text=\"Импортёр: {0}\" BarcodeFormat=\"\" Fields=\"[&quot;SupplierName&quot;]\" id=\"14\"><Cell vertex=\"1\" connectable=\"0\" parent=\"1\"><Geometry _x=\"8.49999975\" _y=\"67\" _width=\"147.5\" _height=\"7\" as=\"geometry\"/><Object fontSize=\"4\" align=\"left\" verticalAlign=\"top\" whiteSpace=\"wrap\" overflow=\"hidden\" fontFamily=\"Arial\" fontStyle=\"1\" rotation=\"0\" fontColor=\"black\" fillColor=\"#ffffff\" strokeColor=\"#2946eb\" strokeWidth=\"0.5\" labelPadding=\"0\" as=\"style\"><Array as=\"baseStyleNames\"><add value=\"yeah\"/></Array></Object></Cell></div><div Text=\"{0}\" BarcodeFormat=\"\" Fields=\"[&quot;Ean&quot;]\" id=\"15\"><Cell vertex=\"1\" connectable=\"0\" parent=\"1\"><Geometry _x=\"82\" _y=\"85\" _width=\"51.5\" _height=\"10\" as=\"geometry\"/><Object fontSize=\"7\" align=\"center\" verticalAlign=\"top\" whiteSpace=\"wrap\" overflow=\"hidden\" fontFamily=\"Arial\" fontStyle=\"1\" rotation=\"0\" fontColor=\"black\" fillColor=\"#ffffff\" strokeColor=\"#2946eb\" strokeWidth=\"0.5\" labelPadding=\"0\" as=\"style\"><Array as=\"baseStyleNames\"><add value=\"yeah\"/></Array></Object></Cell></div><div Text=\"{0}\" BarcodeFormat=\"128\" Fields=\"[&quot;Ean&quot;]\" id=\"16\"><Cell vertex=\"1\" connectable=\"0\" parent=\"1\"><Geometry _x=\"62\" _y=\"95\" _width=\"94\" _height=\"12\" TRANSLATE_CONTROL_POINTS=\"0\" as=\"geometry\"/><Object fontSize=\"8\" align=\"left\" verticalAlign=\"top\" whiteSpace=\"wrap\" overflow=\"hidden\" fontFamily=\"Arial\" fontStyle=\"0\" rotation=\"0\" fontColor=\"black\" fillColor=\"#ffffff\" strokeColor=\"#2946eb\" strokeWidth=\"0.5\" labelPadding=\"0\" as=\"style\"><Array as=\"baseStyleNames\"><add value=\"yeah\"/></Array></Object></Cell></div></root></GraphDataModel>"
```

**Comment by g136660** [comment] 2023-06-01 08:21
"scripts": {
    "start": "rimraf ./build && react-scripts start",
    "build": "rimraf ./build && react-scripts build && npx react-inject-env set"
  },

**Comment by tbouffard** [comment] 2023-06-06 09:56
This looks like a duplicate of #169

**Comment by tbouffard** [comment] 2023-12-19 05:51
Closing as duplicate of #169

**Closed as not planned by tbouffard** 2023-12-19 05:51 UTC
Labels: bug, duplicate
